using System;
using System.Collections;
using System.Drawing;

namespace OpenDentBusiness{

	///<summary>The 'buttons' to show in the Chart module.  They must have items attached in order to do anything.</summary>
	[Serializable]
	public class ProcButton:TableBase {
		///<summary>Primary key</summary>
		[CrudColumn(IsPriKey=true)]
		public long ProcButtonNum;
		///<summary>The text to show on the button.</summary>
		public string Description;
		///<summary>Order that they will show in the Chart module.</summary>
		public int ItemOrder;
		///<summary>FK to definition.DefNum.</summary>
		public long Category;
		///<summary>If no image, then the clob will be an empty string.  In this case, the bitmap will be null when loaded from the database.</summary>
		[CrudColumn(SpecialType=CrudSpecialColType.TextIsClob)]
		public string ButtonImage;
		///<summary>Only useful for procedure buttons which cause more than one procedure to be charted.  Example: Crown (D code) and Delivery (N code).
		///Causes the procedures generated by this procedure button to be grouped using links in the procmultivisit table.</summary>
		public bool IsMultiVisit;

		///<summary></summary>
		public ProcButton Copy() {
			return (ProcButton)MemberwiseClone();
		}

		
	}

	

	


}










