using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using CodeBase;

namespace OpenDentBusiness {
	public enum EnumStaticTextField {
		activeAllergies, 
		activeProblems, 
		address,
		age,
		apptsAllFuture,
		apptDateMonthSpelled,
		apptModNote,
		apptProcs,
		apptProvNameFormal,
		balTotal,
		bal_0_30,
		bal_31_60,
		bal_61_90,
		balOver90,
		balInsEst,
		balTotalMinusInsEst,
		BillingType,
		Birthdate,
		carrierName,
		carrier2Name,
		carrierAddress,
		carrier2Address,
		carrierCityStZip,
		carrier2CityStZip,
		ChartNumber,
		cityStateZip,
		clinicDescription,
		clinicAddress,
		clinicCityStZip,
		clinicPhone,
		clinicPatDescription,
		clinicPatAddress,
		clinicPatCityStZip,
		clinicPatPhone,
		clinicCurDescription,
		clinicCurAddress,
		clinicCurCityStZip,
		clinicCurPhone,
		currentMedications,
		DateFirstVisit,
		dateLastAppt,
		dateLastBW,
		dateLastExam,
		dateLastPanoFMX,
		dateLastPerio,
		dateLastProphy,
		dateLastSrp,
		dateOfLastSavedTP,
		dateRecallDue,
		dateTimeLastAppt,
		dateTodayLong,
		dateToday,
		dueForBWYN,
		dueForPanoYN,
		Email,
		famFinNote,
		famFinUrgNote,
		famPopups,
		famRecallDue,
		gender,
		genderHeShe,
		genderheshe,
		genderHimHer,
		genderhimher,
		genderHimselfHerself,
		genderhimselfherself,
		genderHisHer,
		genderhisher,
		genderHisHers,
		genderhishers,
		guarantorHmPhone,
		guarantorNameF,
		guarantorNameFL,
		guarantorNameL,
		guarantorNamePref,
		guarantorNameLF,
		guarantorWirelessPhone,
		guarantorWkPhone,
		HmPhone,
		insAnnualMax,
		insDeductible,
		insDeductibleUsed,
		insEmployer,
		insFeeSchedule,
		insFreqBW,
		insFreqExams,
		insFreqPanoFMX,
		insPending,
		insPercentages,
		insPlanGroupName,
		insPlanGroupNumber,
		insPlanNote,
		insRemaining,
		insSubBirthDate,
		insSubNote,
		insType,
		insUsed,
		ins2AnnualMax,
		ins2Deductible,
		ins2DeductibleUsed,
		ins2Employer,
		ins2FreqBW,
		ins2FreqExams,
		ins2FreqPanoFMX,
		ins2Pending,
		ins2Percentages,
		ins2PlanGroupName,
		ins2PlanGroupNumber,
		ins2Remaining,
		ins2Used,
		medicalSummary,
		MedUrgNote,
		nameF,
		nameFL,
		nameFLFormal,
		nameL,
		nameLF,
		nameMI,
		namePref,
		namePreferredOrFirst,
		nextSchedApptDate,
		nextSchedApptDateT,
		nextSchedApptsFam,
		patientPortalCredentials,
		PatNum,
		plannedAppointmentInfo,
		practiceTitle,
		premedicateYN,
		priProvNameFormal,
		recallInterval,
		recallScheduledYN,
		referredFrom,
		referredTo,
		salutation,
		serviceNote,
		siteDescription,
		SSN,
		subscriberID,
		subscriberNameFL,
		subscriber2NameFL,
		timeNow,
		tpResponsPartyAddress,
		tpResponsPartyCityStZip,
		tpResponsPartyNameFL,
		treatmentNote,
		treatmentPlanProcs,
		treatmentPlanProcsPriority,
		WirelessPhone,
		WkPhone,
	}

	///<summary>Bitwise flag indicating a dependency upon a certain StaticTextData field.</summary>
	[Flags]
	public enum StaticTextFieldDependency : long {
		None=					0b0,
		Pat=					0b1,
		Fam=					0b10,
		PatNote=				0b100,
		ListRefAttaches=		0b1000,
		ListInsSubs=			0b10000,
		ListInsPlans=			0b100000,
		ListPatPlans=			0b1000000,
		ListBenefits=			0b10000000,
		HistList=				0b100000000,
		ListTreatPlans=			0b1000000000,
		ListRecallsForFam=		0b10000000000,
		ListAppts=				0b100000000000,
		ListFutureApptsForFam=	0b1000000000000,
		ListDiseases=			0b10000000000000,
		ListAllergies=			0b100000000000000,
		ListMedicationPats=		0b1000000000000000,
		ListFamPopups=			0b10000000000000000,
		ListProceduresSome=		0b100000000000000000,
		ListDocuments=			0b1000000000000000000,
		ListProceduresPat=		0b10000000000000000000,
		ListPlannedAppts=		0b100000000000000000000,
		ListSelectedTpProcs=	0b1000000000000000000000,
	}

	///<summary>This represents a single replacement in static text fields or eForms. This allow us to fill a list of these objects separately from how we go about actually performing the replacements.</summary>
	public class StaticTextReplacement {
		///<summary></summary>
		public EnumStaticTextField StaticTextField;
		public string NewValue;
	}
}
