using System;

namespace OpenDentBusiness {
	[Serializable]
	[CrudTable(IsMissingInGeneral=true,CrudExcludePrefC=true)]
	public class WebChatMessage:TableBase {
		///<summary>Primary key.</summary>
		[CrudColumn(IsPriKey=true)]
		public long WebChatMessageNum;
		///<summary>FK to webchatsession.WebChatSessionNum</summary>
		public long WebChatSessionNum;
		///<summary>Blank when MessageType is System.</summary>
		public string UserName;
		///<summary>Previously this column had a CrudColumn attribute with SpecialType=CrudSpecialColType.TimeStamp.
		///This resulted in the column being set to the current time stamp when it was updated, which was NOT possible until NeedsFollowUp was introduced.
		///We have since removed the CrudColumn attribute and disabled the on-update feature in mysql.
		///We kept the default CURRENT_TIMESTAMP value so that new rows auto insert with the same value in this column as before.
		///You will not see DateT in the CRUD for this table.</summary>
		[CrudColumn(SpecialType=CrudSpecialColType.DateT)]
		public DateTime DateT;
		///<summary>The chat message content.</summary>
		public string MessageText;
		///<summary>Enum:WebChatMessageType Who created the message.</summary>
		public WebChatMessageType MessageType;
		///<summary>Stores the client IP address for this session</summary>
		public string IpAddress;
		///<summary>A flag that technicians can toggle to prevent customer questions from falling through the cracks.</summary>
		public bool NeedsFollowUp;
	}

	///<summary>Describes where the message was generated from.</summary>
	public enum WebChatMessageType {
		///<summary>0-Automatically generated by the chat system.</summary>
		System,
		///<summary>1-A special system message.  Once a message with this type is added to a session, the session is frozen forever.</summary>
		EndSession,
		///<summary>2-Message manually typed by a technician.</summary>
		Technician,
		///<summary>3-Message manually typed by the customer.</summary>
		Customer,
		///<summary>4-Message generated by an AI system.</summary>
		AI,
	}

}