#!/bin/bash
DATE=`date +%Y%m%d`
REVISION=`svn info https://70.90.133.65:23793/svn/opendental/head | grep Revision | tr --delete "Revision: " `
LABEL="opendental-$DATE-$REVISION"
echo $LABEL
rm rf opendental*
svn export https://70.90.133.65:23793/svn/opendental/head opendental
tar -cvzf "$LABEL.tar.gz" opendental/
rm -rf opendental/
