.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\"
.TH nant 1 "2005-05-16"
.SH "NAME"
Open Dental \- Open Source Practice Management
.SH "SYNOPOSIS"
.B opendental
.B Open Dental
is the first dental software written for the .NET framework
.SH "SEE ALSO"
Open Dental web site
.UR http://www.open-dent.com/
http://www.open-dent.com/
.UE
.LP
Man page by Frederik Carlier, made available under the same terms as Open Dental
